---
- name: Run the application container
  docker_container:
    name: simple-api
    image: benoitbassompierre/tp-devops-simple-api
    pull: yes
    ports:
      - "5000:5000"
    networks:
      - name: my_app_net
    restart_policy: always
    env:
      DATABASE_HOST: postgres_db
      DATABASE_PASSWORD: pwd