---
- name: Run reverse proxy container
  docker_container:
    name: proxy
    image: benoitbassompierre/tp-devops-httpd
    pull: yes
    ports:
      - "80:80"
    networks:
      - name: my_app_net