# name: CI devops 2025
# on:
#   #to begin you want to launch this job in main and develop
#   push:
#     branches: [ main, develop ]
#   pull_request:
 
# jobs:
#   test-backend:
#     runs-on: ubuntu-24.04
#     steps:
#      #checkout your github code using actions/checkout@v4
#       - uses: actions/checkout@v4
 
#      #do the same with another action (actions/setup-java@v4) that enable to setup jdk 21
#       - name: Set up JDK 21
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: '21'
 
#      #finally build your app with the latest command
#       - name: Build and test with Maven
#         run: mvn clean verify --file simple-api/pom.xml


name: CI devops 2025
 
on:
  push:
    branches: [ main, develop ]
  pull_request:
 
jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
 
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api
 
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: true
 
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: database
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: true
 
      - name: Build image and push httpd
        uses: docker/build-push-action@v6
        with:
          context: http-server
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: true
    evaluate-performances:
      steps:
      - name: evaluate on sonarflow
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=benoit-bassompierre_tp-devops-correction-docker -Dsonar.organization=benoit-bassompierre -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=43dc2325fb9e3051983626b6bab7b321df8fde71  --file ./simple-api/pom.xml

        
